# Generated by Django 5.2.10 on 2026-01-23 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_open',
        ),
        migrations.AddField(
            model_name='shop',
            name='close_time',
            field=models.TimeField(default=datetime.time(18, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='open_time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='working_days',
            field=models.CharField(default=('Mon', 'Tues', 'Wed', 'Thu', 'Fri'), max_length=50),
            preserve_default=False,
        ),
    ]
