# Generated by Django 5.2.10 on 2026-01-23 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('people_count', models.PositiveIntegerField()),
                ('Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_records', to='queues.shop')),
                ('TimeSlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_records', to='queues.timeslot')),
            ],
        ),
    ]
