# Generated by Django 5.2.10 on 2026-01-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_crowdrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crowdrecord',
            old_name='Shop',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='crowdrecord',
            old_name='TimeSlot',
            new_name='timeslot',
        ),
    ]
